server:
  port: 5001

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: Product-MS
  data:
    mongodb:
      database: demo
      password: demo
      username: demo
      host: localhost
      port: 27018
