server:
  port: 8090

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: Product-MS
  data:
    mongodb:
      database: demo
      password: walid
      username: walid
      host: localhost
      port: 27017

opentracing:
  jaeger:
    udp-sender:
      host: localhost
      port: 6831


